apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-config1
data:
  EMQX_NAME: emqx
  EMQX_CLUSTER__DISCOVERY: k8s
  EMQX_CLUSTER__K8S__APP_NAME: emqx
  EMQX_CLUSTER__K8S__SERVICE_NAME: emqx-service1
  EMQX_CLUSTER__K8S__APISERVER: https://kubernetes.default.svc:443
  EMQX_CLUSTER__K8S__NAMESPACE: default
