apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-config3
data:
  EMQX_NAME: emqx
  EMQX_CLUSTER__DISCOVERY: k8s
  EMQX_CLUSTER__K8S__APP_NAME: emqx
  EMQX_CLUSTER__K8S__SERVICE_NAME: emqx-headless
  EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.docker.internal:6443"
  EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
  EMQX_CLUSTER__K8S__NAMESPACE: default
