apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx-statefulset3
  labels:
    app: emqx
spec:
  replicas: 3
  serviceName: emqx-headless3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      #volumes:
      #  - name: emqx-data
      #    persistentVolumeClaim:
      #      claimName: emqx-pvc
      serviceAccountName: emqx
      containers:
        - name: emqx
          image: emqx/emqx:4.3.7
          ports:
            - name: mqtt
              containerPort: 1883
            - name: mqttssl
              containerPort: 8883
            - name: mgmt
              containerPort: 8081
            - name: ws
              containerPort: 8083
            - name: wss
              containerPort: 8084
            - name: dashboard
              containerPort: 18083
          envFrom:
            - configMapRef:
                name: emqx-config3
          volumeMounts:
            - name: emqx-pvc #emqx-data
              mountPath: "/opt/emqx/data/mnesia"
  volumeClaimTemplates:
    - metadata:
        name: emqx-pvc
        #annotations:
        #  volume.alpha.kubernetes.io/storage-class: manual
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
