# Create a pod containing the PHP-FPM application (k8s-php)
# and nginx, each mounting the `shared-files` volume to their
# respective /var/www/html directories.

kind: Pod
apiVersion: v1
metadata:
  name: k8s-nginx-php
  labels:
    app: k8s-nginx-php
spec:
  volumes:
    # Create the shared files volume to be used in both pods
    - name: shared-files
      emptyDir: {}
    
    # Add the ConfigMap we declared above as a volume for the pod
    - name: k8s-nginx-volume
      configMap:
        name: k8s-nginx-config

  containers:
    # Our PHP-FPM application
    - image: k8s-php:1.0.0
      name: app
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      # Important! After this container has started, the PHP files
      # in our Docker image aren't in the shared volume. We need to 
      # get them into the shared volume. If we tried to write directly
      # to this volume from our Docker image the files wouldn't appear
      # in the nginx container.
      #
      # So, after the container has started, copy the PHP files from this
      # container's local filesystem (/app -- added via the Docker image) 
      # to the shared volume, which is mounted at /var/www/html.
      lifecycle:
        postStart:
          exec:
            #command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
            command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html && chmod 755 -R /var/www/html && chown www-data:www-data -R /var/www/html"]
            #command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html && chown www-data:www-data -R /var/www/html"]
    
    # Our nginx container, which uses the configuration declared above,
    # along with the files shared with the PHP-FPM app.
    - image: nginx:1.21.0
      name: nginx
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: k8s-nginx-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf