apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      volumes:
        - name: tut02-volume
          persistentVolumeClaim:
            claimName: tut02-volume
        - name: config
          configMap:
            name: tut02-nginx-config
            items:
              - key: config
                path: site.conf
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tut02-volume
              mountPath: /var/www/html
            - name: config
              mountPath: /etc/nginx/conf.d
