apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-www-claim
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi