apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: volume-container
        image: tut01-php:1.0.0
        volumeMounts:
        - mountPath: /var/www/html
          name: app-volume
        lifecycle:
          postStart:
            exec:
              command:
                [
                  "/bin/sh",
                  "-c",
                  "cp -r /app/. /var/www/html && chmod 755 -R /var/www/html && chown www-data:www-data -R /var/www/html",
                ]
      volumes:
        - name: app-volume
          emptyDir: {}