# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: php7-service
#   namespace: default
#   labels:
#     app: php7
# spec:
#   ports:
#     - name: listener
#       protocol: TCP
#       port: 9000
#       targetPort: 9000
#   selector:
#     app: php7
#   # Minikube needs NodePort to work.
#   # type: ClusterIP
#   type: NodePort
#   sessionAffinity: None
# ---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  sessionAffinity: None
